apiVersion: v2
type: application
name: fmtm
description: Field Tasking Manager - coordinated field mapping.
version: "0.1.0"
appVersion: "2025.3.1"
maintainers:
- email: sam.woodcock@hotosm.org
  name: Sam Woodcock
home: https://github.com/hotosm/field-tm/tree/main/chart
icon: https://fmtm.hotosm.org/favicon.png
dependencies:
  - name: postgresql
    version: 15.2.2
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: db.enabled
    alias: db
  - name: minio
    version: 5.1.0
    repository: https://charts.min.io
    condition: s3.enabled
    alias: s3
