[project]
name = "osm-fieldwork"
version = "0.22.0"
description = "Processing field data from ODK to OpenStreetMap format."
authors = [
    {name = "Rob Savoye", email = "rob.savoye@hotosm.org"},
    {name = "Sam Woodcock", email = "sam.woodcock@hotosm.org"},
    {name = "Sujan Adhikari", email = "adhikarisujan.naxa@gmail.com"},
]
dependencies = [
    "geojson>=3.0.0",
    "PyYAML>=6.0.0",
    "segno>=1.5.2",
    "pandas>=1.5.0",
    "python-calamine>=0.3.1",
    "openpyxl>=3.0.10",
    "requests>=2.26.0",
    "aiohttp>=3.8.4",
    "osm-rawdata>=0.1.7",
]
requires-python = ">=3.10"
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["hot", "odk", "openstreetmap", "fmtm"]
classifiers = [
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
homepage = "https://hotosm.github.io/osm-fieldwork"
documentation = "https://hotosm.github.io/osm-fieldwork"
repository = "https://github.com/hotosm/field-tm/blob/main/src/backend/packages/osm-fieldwork"

[dependency-groups]
docs = [
    "mkdocs>=1.5.2",
    "mkdocs-material>=9.2.3",
    "mkdocstrings-python>=1.5.1",
    "mkdocs-exclude>=1.0.2",
    "mkdocs-git-revision-date-localized-plugin>=1.2.4",
    "mdx-truly-sane-lists>=1.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["osm_fieldwork"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.22.0"
version_files = [
    "pyproject.toml:version",
    "osm_fieldwork/__version__.py",
    "Makefile:VERSION",
]
update_changelog_on_bump = true

[tool.ruff]
fix = true
line-length = 132
target-version = "py310"
exclude = [
    ".git",
    ".ruff_cache",
    ".vscode",
    "build",
    "dist",
    "osm_fieldwork/__version__.py",
    # Temp workaround until osm-fieldwork linting all fixed
    "osm_fieldwork",
    "tests",
]
[tool.ruff.lint]
select = ["I", "E", "W", "D", "B", "F", "N", "Q"]
ignore = ["N805", "B008"]
[tool.ruff.lint.per-file-ignores]
"osm_fieldwork/basemapper.py" = ["N802"]
[tool.ruff.lint.pydocstyle]
convention = "google"

# TODO update these from PDM --> uv setup
[project.scripts]
basemapper = "osm_fieldwork.basemapper:main"
osm2favorites = "osm_fieldwork.osm2favorities:main"
odk2osm = "osm_fieldwork.odk2osm:main"
odk_client = "osm_fieldwork.odk_client:main"
make_data_extract = "osm_fieldwork.make_data_extract:main"
fmtm_xlsform = "osm_fieldwork.update_xlsform:main"
