# Copyright (c) 2022, 2023 Humanitarian OpenStreetMap Team
# This file is part of FMTM.
#
#     FMTM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     FMTM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with FMTM.  If not, see <https:#www.gnu.org/licenses/>.
#

name: fmtm-stage

volumes:
  nginx-configs:
    name: fmtm-nginx-configs-${GIT_BRANCH}
  fmtm_frontend:
    name: fmtm-frontend-${GIT_BRANCH}
  fmtm_mapper_frontend:
    name: fmtm-mapper-frontend-${GIT_BRANCH}
  fmtm_db_data:
    name: fmtm-db-data-${GIT_BRANCH}
  fmtm_data:
    name: fmtm-s3-data-${GIT_BRANCH}
  fmtm_logs:
    name: fmtm-logs-${GIT_BRANCH}
  fmtm_images:
    name: fmtm-images-${GIT_BRANCH}
  fmtm_tiles:
    name: fmtm-tiles-${GIT_BRANCH}
  certs:
    name: fmtm-certs-${GIT_BRANCH}
  certbot_data:
    name: fmtm-certbot-data-${GIT_BRANCH}
  central_db_data:
    name: fmtm-central-db-data-${GIT_BRANCH}
  central_frontend:
    name: fmtm-central-frontend-${GIT_BRANCH}

networks:
  fmtm-net:
    name: fmtm-${GIT_BRANCH}
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24

services:
  proxy:
    extends:
      file: compose.development.yaml
      service: proxy
  proxy-setup:
    extends:
      file: compose.development.yaml
      service: proxy-setup
    volumes:
      - nginx-configs:/etc/nginx
      - fmtm_frontend:/var/www/html/stage.fmtm.hotosm.org:ro
      - fmtm_mapper_frontend:/var/www/html/mapper.stage.fmtm.hotosm.org:ro
      - central_frontend:/var/www/html/odk.stage.fmtm.hotosm.org:ro
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      SERVER_NAME: stage.fmtm.hotosm.org mapper.stage.fmtm.hotosm.org api.stage.fmtm.hotosm.org s3.stage.fmtm.hotosm.org sync.stage.fmtm.hotosm.org odk.stage.fmtm.hotosm.org
      api.stage.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://api:8000
      api.stage.fmtm.hotosm.org_MAX_CLIENT_SIZE: 1G
      s3.stage.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://s3:9000
      s3.stage.fmtm.hotosm.org_MAX_CLIENT_SIZE: 10G
      sync.stage.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://electric:3000
      sync.stage.fmtm.hotosm.org_MAX_CLIENT_SIZE: 1G
      odk.stage.fmtm.hotosm.org_REVERSE_PROXY_HOST: http://central:8383
      odk.stage.fmtm.hotosm.org_REVERSE_PROXY_URL: ~ ^/v\d
      # buffer requests, but not responses, so streaming out works
      odk.stage.fmtm.hotosm.org_REVERSE_PROXY_BUFFERING: no
      odk.stage.fmtm.hotosm.org_MAX_CLIENT_SIZE: 500m
  api:
    extends:
      file: compose.development.yaml
      service: api
  ui:
    extends:
      file: compose.development.yaml
      service: ui
  central:
    extends:
      file: compose.development.yaml
      service: central
  central-webhook:
    extends:
      file: compose.development.yaml
      service: central-webhook
  pyxform:
    extends:
      file: compose.development.yaml
      service: pyxform
  central-ui:
    extends:
      file: compose.development.yaml
      service: central-ui
  s3:
    extends:
      file: compose.development.yaml
      service: s3
  fmtm-db:
    extends:
      file: compose.development.yaml
      service: fmtm-db
  electric:
    extends:
      file: compose.development.yaml
      service: electric
  central-db:
    extends:
      file: compose.development.yaml
      service: central-db
  migrations:
    extends:
      file: compose.development.yaml
      service: migrations
  scheduler:
    extends:
      file: compose.development.yaml
      service: scheduler
  backups:
    image: "ghcr.io/hotosm/fmtm/backend:${GIT_BRANCH}"
    depends_on:
      fmtm-db:
        condition: service_healthy
      central-db:
        condition: service_healthy
      s3:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - fmtm-net
    entrypoint: ["/backup-entrypoint.sh"]
    restart: "on-failure:2"
    healthcheck:
      test: pg_isready -U ${FMTM_DB_USER} -d ${FMTM_DB_NAME}
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
