name: ðŸ”§ Build CI Img

on:
  # Push includes PR merge
  push:
    branches:
      - main
      - staging
      - development
    paths:
      # Workflow is triggered only if deps change
      - "src/backend/pyproject.toml"
      - "src/backend/Dockerfile"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  backend-ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@1.1.2
    with:
      context: src/backend
      build_target: ci
      image_tags: |
        "ghcr.io/${{ github.repository }}/backend:ci-${{ github.ref_name }}"
